package hua.tung.smk.pandaspbt.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "BOOK_INFO".
 */
@Entity
public class BookInfo {

    @Id(autoincrement = true)
    private Long book_info_id;
    private String book_name;
    private String book_code;
    private String book_type;
    private String form;
    private String book_publisher;
    private String book_price;
    private String book_symbol;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public BookInfo() {
    }

    public BookInfo(Long book_info_id) {
        this.book_info_id = book_info_id;
    }

    @Generated
    public BookInfo(Long book_info_id, String book_name, String book_code, String book_type, String form, String book_publisher, String book_price, String book_symbol) {
        this.book_info_id = book_info_id;
        this.book_name = book_name;
        this.book_code = book_code;
        this.book_type = book_type;
        this.form = form;
        this.book_publisher = book_publisher;
        this.book_price = book_price;
        this.book_symbol = book_symbol;
    }

    public Long getBook_info_id() {
        return book_info_id;
    }

    public void setBook_info_id(Long book_info_id) {
        this.book_info_id = book_info_id;
    }

    public String getBook_name() {
        return book_name;
    }

    public void setBook_name(String book_name) {
        this.book_name = book_name;
    }

    public String getBook_code() {
        return book_code;
    }

    public void setBook_code(String book_code) {
        this.book_code = book_code;
    }

    public String getBook_type() {
        return book_type;
    }

    public void setBook_type(String book_type) {
        this.book_type = book_type;
    }

    public String getForm() {
        return form;
    }

    public void setForm(String form) {
        this.form = form;
    }

    public String getBook_publisher() {
        return book_publisher;
    }

    public void setBook_publisher(String book_publisher) {
        this.book_publisher = book_publisher;
    }

    public String getBook_price() {
        return book_price;
    }

    public void setBook_price(String book_price) {
        this.book_price = book_price;
    }

    public String getBook_symbol() {
        return book_symbol;
    }

    public void setBook_symbol(String book_symbol) {
        this.book_symbol = book_symbol;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
