package hua.tung.smk.pandaspbt.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentInfoDaoConfig;
    private final DaoConfig borrowReturnDaoConfig;
    private final DaoConfig bookInfoDaoConfig;

    private final StudentInfoDao studentInfoDao;
    private final BorrowReturnDao borrowReturnDao;
    private final BookInfoDao bookInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentInfoDaoConfig = daoConfigMap.get(StudentInfoDao.class).clone();
        studentInfoDaoConfig.initIdentityScope(type);

        borrowReturnDaoConfig = daoConfigMap.get(BorrowReturnDao.class).clone();
        borrowReturnDaoConfig.initIdentityScope(type);

        bookInfoDaoConfig = daoConfigMap.get(BookInfoDao.class).clone();
        bookInfoDaoConfig.initIdentityScope(type);

        studentInfoDao = new StudentInfoDao(studentInfoDaoConfig, this);
        borrowReturnDao = new BorrowReturnDao(borrowReturnDaoConfig, this);
        bookInfoDao = new BookInfoDao(bookInfoDaoConfig, this);

        registerDao(StudentInfo.class, studentInfoDao);
        registerDao(BorrowReturn.class, borrowReturnDao);
        registerDao(BookInfo.class, bookInfoDao);
    }
    
    public void clear() {
        studentInfoDaoConfig.clearIdentityScope();
        borrowReturnDaoConfig.clearIdentityScope();
        bookInfoDaoConfig.clearIdentityScope();
    }

    public StudentInfoDao getStudentInfoDao() {
        return studentInfoDao;
    }

    public BorrowReturnDao getBorrowReturnDao() {
        return borrowReturnDao;
    }

    public BookInfoDao getBookInfoDao() {
        return bookInfoDao;
    }

}
