package hua.tung.smk.pandaspbt.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "STUDENT_INFO".
 */
@Entity
public class StudentInfo {

    @Id(autoincrement = true)
    private Long student_id;
    private String student_name;
    private String student_no;
    private String student_class;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public StudentInfo() {
    }

    public StudentInfo(Long student_id) {
        this.student_id = student_id;
    }

    @Generated
    public StudentInfo(Long student_id, String student_name, String student_no, String student_class) {
        this.student_id = student_id;
        this.student_name = student_name;
        this.student_no = student_no;
        this.student_class = student_class;
    }

    public Long getStudent_id() {
        return student_id;
    }

    public void setStudent_id(Long student_id) {
        this.student_id = student_id;
    }

    public String getStudent_name() {
        return student_name;
    }

    public void setStudent_name(String student_name) {
        this.student_name = student_name;
    }

    public String getStudent_no() {
        return student_no;
    }

    public void setStudent_no(String student_no) {
        this.student_no = student_no;
    }

    public String getStudent_class() {
        return student_class;
    }

    public void setStudent_class(String student_class) {
        this.student_class = student_class;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
